### ISSUE TITLE
Error on add_suplot part of display_similar_products

### ISSUE THREAD

**Issue by smart-patrol** [aws-samples/aws-sagemaker-pytorch-shop-by-style#1]
For the line with:

`def display_similiar_products(product_info) :
    count = 0
    columns = 7
    BATCHES_TO_DISPLAY = 3

    fig = plt.figure(figsize=(columns*2, BATCHES_TO_DISPLAY*3))
    fig.subplots_adjust(wspace=.1)

    products = product_info['sim']
    print(product_info['n'])
    
    for (index, row) in products[0:columns*BATCHES_TO_DISPLAY].iterrows() :

        count += 1
        ax = fig.add_subplot(BATCHES_TO_DISPLAY, columns, count)   
        ax.set_title(round(row['sim'],5))
        ax.set_xticklabels([])
        ax.set_yticklabels([])
        plt.imshow(plt.imread(os.path.join(LOCAL_DATA_DIR,row['img'])))
        
    plt.show()`

I am getting the following error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-32-1bc5c57dd7e3> in <module>()
----> 1 display_similar_products(SAMPLE_PRODUCTS[3])

<ipython-input-27-5f111c72de49> in display_similar_products(product_info)
     28     for (index, row) in products[0:columns*BATCHES_TO_DISPLAY].iterrows():
     29         count += 1
---> 30         ax = fig.add_suplot(BATCHES_TO_DISPLAY, columns, count)
     31         ax.set_title(round(row['sim'],5))
     32         ax.set_xticklabels([])

AttributeError: 'Figure' object has no attribute 'add_suplot'`

**Comment by dylan-tong-aws** [comment]
Hi, this notebook was design and tested to run in SageMaker notebook environments. It's difficult for me to tell why you're running into this error. It's likely . an issue related to the Matplotlib libraries in your environment (https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_subplot). I recommend running the notebook in SageMaker on the conda_pytorch_p36 kernel (without modifying the kernel). I've re-tested the notebook, and encountered no issues within this SageMaker environment.
